; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = lilygo-t3-s3
framework = arduino
lib_deps = 
    jgromes/RadioLib @ ^6.6.0  ; This pulls the latest stable version
    lewisxhe/XPowersLib @ ^0.1.7
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.9
    

[env:sender]
build_flags = -D ROLE_SENDER
upload_port = COM10 
; port is extremely useful to set for both devices connected at once

[env:receiver]
build_flags = -D ROLE_RECEIVER
upload_port = COM11
; port is extremely useful to set for both devices connected at once

